#!/usr/bin/env bash
set -euo pipefail

# Path to target .env (default: project root .env)
ENV_FILE="${1:-./.env}"

# Key/values to enforce (from env_file_template.txt lines 3-38)
declare -A KV=(
  [BROKER_PRIMARY]="PLACEHOLDER_BROKER_PRIMARY"
  [BROKER_FAILOVER_TIMEOUT]="30"
  [RESET_THRESHOLD]="3000"
  [SEND_ANALYTICS_PIPELINE]="PLACEHOLDER_SEND_ANALYTICS_PIPELINE"
  [SEND_EVENTS_PIPELINE]="PLACEHOLDER_SEND_EVENTS_PIPELINE"
  [LOG_TOPIC]="error_log"
  [AWS_PRIMARY_KEY]="PLACEHOLDER_AWS_PRIMARY_KEY"
  [AWS_PRIMARY_SECRET]="PLACEHOLDER_AWS_PRIMARY_SECRET"
  [AWS_PRIMARY_REGION]="ap-south-1"
  [AWS_PRIMARY_BUCKET_NAME]="PLACEHOLDER_AWS_PRIMARY_BUCKET_NAME"
  [AWS_PRIMARY_ORG_IMG_FN]="violationoriginalimages/"
  [AWS_PRIMARY_VIDEO_FN]="PLACEHOLDER_AWS_PRIMARY_VIDEO_FN"
  [AWS_PRIMARY_CGI_FN]="PLACEHOLDER_AWS_PRIMARY_CGI_FN"
  [AWS_PRIMARY_ENDPOINT]="PLACEHOLDER_AWS_PRIMARY_ENDPOINT"
  [API_AWS_PRIMARY_KEY]="minio"
  [API_AWS_PRIMARY_SECRET]="PLACEHOLDER_API_AWS_PRIMARY_SECRET"
  [API_AWS_PRIMARY_REGION]="ap-south-1"
  [API_AWS_PRIMARY_BUCKET_NAME]="PLACEHOLDER_API_AWS_PRIMARY_BUCKET_NAME"
  [API_AWS_PRIMARY_ORG_IMG_FN]="violationoriginalimages/"
  [API_AWS_PRIMARY_VIDEO_FN]="PLACEHOLDER_API_AWS_PRIMARY_VIDEO_FN"
  [API_AWS_PRIMARY_CGI_FN]="PLACEHOLDER_API_AWS_PRIMARY_CGI_FN"
  [API_AWS_PRIMARY_ENDPOINT]="http://5200001-minio.arresto.io"
  [API_POST_URL]="PLACEHOLDER_API_POST_URL"
  [API_REQUEST_TIMEOUT]="30"
  [API_MAX_RETRIES]="3"
  [S3_FAILOVER_TIMEOUT]="30"
  [S3_UPLOAD_RETRIES]="3"
  [WS_SERVER_URL]="PLACEHOLDER_WS_SERVER_URL"
  [LOG_LEVEL]="INFO"
)

touch "$ENV_FILE"

for key in "${!KV[@]}"; do
  value="${KV[$key]}"
  if grep -qE "^${key}=" "$ENV_FILE"; then
    # Replace existing line
    sed -i.bak -E "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    # Append if missing
    echo "${key}=${value}" >> "$ENV_FILE"
  fi
done

echo "Updated $ENV_FILE with template values (existing keys replaced, others appended)."